apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: {{ .Values.server.name }}
  namespace: mlperf
spec:
  type: ClusterSetIP
  ports:
  - port: {{ .Values.client.serviceImportPort }}
    protocol: TCP
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Values.server.name }}-import
  namespace: mlperf
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: {{ .Values.server.name }}
      namespace: mlperf
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.client.clustersAffinity }}
        - {{ . }}
        {{- end }}