apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: mlperf
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repo }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: SERVER_ADDR
          value: "http://derived-{{ .Values.serviceImportName}}.mlperf.svc.cluster.local"