apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: {{ .Values.serviceImportName }}
  namespace: mlperf
spec:
  type: ClusterSetIP
  ports:
  - port: {{ .Values.serviceImportPort }}
    protocol: TCP