apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: mlperf
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repo }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.image.port }}
        {{- if .Values.monitor }}
        env:
          - name: MONITOR
            value: "True"
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: mlperf
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - name: {{ .Values.name }}-default
    port: 80
    targetPort: 8000
  - name: {{ .Values.name }}-monitor
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
---
{{- if .Values.monitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: mlperf
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
  - port: {{ .Values.name }}-monitor
{{- end }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Values.name }}
  namespace: mlperf
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: mlperf
      name: {{ .Values.name }}
    - apiVersion: v1
      kind: Service
      namespace: mlperf
      name: {{ .Values.name }}
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      namespace: mlperf
      name: {{ .Values.name }}
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clustersAffinity }}
        - {{ . }}
        {{- end }}
