name: mlperf-server
deleteEndpointSlices: delete_endpoint_slices
image:
  repo: "tl2140"
  image: "mlperf-slient-server"
  tag: "server_cpu"
  port: 8000
clustersAffinity:
  - karmada-cluster-2
serviceExportPort: 80