apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: {{ .Values.server.name }}
  namespace: mlperf
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Values.server.name }}-export
  namespace: mlperf
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: {{ .Values.server.name }}
      namespace: mlperf
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.server.clustersAffinity }}
        - {{ . }}
        {{- end }}
