apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: {{ .Values.name }}
  namespace: nephele-monitor-test

---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Values.name }}-export
  namespace: nephele-monitor-test
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: {{ .Values.name }}
      namespace: nephele-monitor-test
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clustersAffinity }}
        - {{ . }}
        {{- end }}

