apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: {{ .Values.name }}
  namespace: nephele-monitor-test
spec:
  type: ClusterSetIP
  ports:
  - name: {{ .Values.name }}-rest
    port: {{ .Values.image.port_rest }} 
    protocol: TCP
  - name: {{ .Values.name }}-monitor
    port: {{ .Values.image.port_prometheus }} 
    protocol: TCP

---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Values.name }}-import
  namespace: nephele-monitor-test
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: {{ .Values.name }}
      namespace: nephele-monitor-test
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clustersAffinityServiceImport }}
        - {{ . }}
        {{- end }}

