apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbacDeleteEndpointSlicesHook }}-sa
  namespace: mlperf
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbacDeleteEndpointSlicesHook }}
  namespace: mlperf
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
rules:
- apiGroups: [""]
  resources: ["endpointslices"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbacDeleteEndpointSlicesHook }}-binding
  namespace: mlperf
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbacDeleteEndpointSlicesHook }}-sa
  namespace: mlperf
roleRef:
  kind: Role
  name: {{ .Values.rbacDeleteEndpointSlicesHook }}
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Values.rbacDeleteEndpointSlicesHook }}-policy
  namespace: mlperf
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ServiceAccount
      name: {{ .Values.rbacDeleteEndpointSlicesHook }}-sa
      namespace: mlperf
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: {{ .Values.rbacDeleteEndpointSlicesHook }}
      namespace: mlperf
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: {{ .Values.rbacDeleteEndpointSlicesHook }}-binding
      namespace: mlperf
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clustersAffinity }}
        - {{ . }}
        {{- end }}