name: nephele-monitor-g
monitor: true
image:
  repo: "tl2140"
  image: "nephele-monitor-test"
  tag: "gauge-test"
  port_prometheus: 8000
  port_rest: 5000
clustersAffinity:
  - karmada-cluster-1
clustersAffinityServiceImport:
  - karmada-cluster-2
